# Generated by scripts/homebrew-formula.sh in ritru-labs/mellow. Do not edit.
class Mellow < Formula
  desc "Calm terminal text editor with no modes to learn"
  homepage "https://github.com/ritru-labs/mellow"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.2.0/mellow-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "6ab5cc4017d897940abf319a29ea89c573ed8ae9b49282bbfb967695a2236ac2"
    end
    on_intel do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.2.0/mellow-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "49b8ef5395f557d57070f74ceffb458fac2549352f84913ed3ff54fd5ca53a32"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.2.0/mellow-0.2.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "edca281d502d5d661702aa3194e153b455918ce5613c3b5315964a14e26bbe87"
    end
    on_intel do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.2.0/mellow-0.2.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "9d14c66ace70a45b04489b3d6e3754f1f9721f20fe4905a28091a466eb903cb5"
    end
  end

  def install
    bin.install "mellow"
  end

  test do
    assert_equal "mellow #{version}", shell_output("#{bin}/mellow --version").strip
  end
end
