# Generated by scripts/homebrew-formula.sh in ritru-labs/mellow. Do not edit.
class Mellow < Formula
  desc "Calm terminal text editor with no modes to learn"
  homepage "https://github.com/ritru-labs/mellow"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.3.0/mellow-0.3.0-aarch64-apple-darwin.tar.gz"
      sha256 "10c386ddaa9ac53c6cfd261d98edcf57fae081bd925c7e663d51613074490fd0"
    end
    on_intel do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.3.0/mellow-0.3.0-x86_64-apple-darwin.tar.gz"
      sha256 "9cc9fda03e4dd8a20a60f2553927452ad598e72455ac792cc943297f45d71376"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.3.0/mellow-0.3.0-aarch64-unknown-linux-musl.tar.gz"
      sha256 "905af95bb657a19509db86899338967e985a6c408a1a4303a469e143f54bd622"
    end
    on_intel do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.3.0/mellow-0.3.0-x86_64-unknown-linux-musl.tar.gz"
      sha256 "69288941d5a9058dce6111b97e733e68b2304f7211921336127b73eb109a113f"
    end
  end

  def install
    bin.install "mellow"
  end

  test do
    assert_equal "mellow #{version}", shell_output("#{bin}/mellow --version").strip
  end
end
