# Generated by scripts/homebrew-formula.sh in ritru-labs/mellow. Do not edit.
class Mellow < Formula
  desc "Calm terminal text editor with no modes to learn"
  homepage "https://github.com/ritru-labs/mellow"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.2.1/mellow-0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "84f96c0a1a9f3c9087383fa551fea97b808e0bf091a90cf32fc46ad215c0177b"
    end
    on_intel do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.2.1/mellow-0.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "602f97234d944ab51ac1e4d8607d43f4b9d41a7139cbbf778e318a82b7cb6c54"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.2.1/mellow-0.2.1-aarch64-unknown-linux-musl.tar.gz"
      sha256 "4a6114fe8298d1cbfa04a88700a9acdb4708cfe426d13a617b0b2de1d032d56a"
    end
    on_intel do
      url "https://github.com/ritru-labs/mellow/releases/download/v0.2.1/mellow-0.2.1-x86_64-unknown-linux-musl.tar.gz"
      sha256 "d482be2d8358da7ead47f6f00e2cf183e502211d8ed25d76aca727638949f6e0"
    end
  end

  def install
    bin.install "mellow"
  end

  test do
    assert_equal "mellow #{version}", shell_output("#{bin}/mellow --version").strip
  end
end
